[package]
name = "windows"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
path = "/git/windows-rs/crates/libs/windows"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]